### GET gifts
GET http://127.0.0.1:8080/api/gifts/EQDhnTXusaL_Zgn57mw1H-QQ1DdQ78DGJ9pUElBvF0TfhrEJ


### GET gifts
GET http://127.0.0.1:8080/api/gifts/EQDQkzpqk1-o4OaOIr_KFyB9HfPpFNZ7fMT7rP1ybkizSYZa


### GET gifts
GET http://127.0.0.1:8080/api/gifts/EQAs3yBRXklBI3lHkWA2Y1V7oX_XvhVSfRbAIugY4C7Lx1sY



### GET gifts

GET https://toncenter.com/api/v3/nft/items?owner_address=EQDQkzpqk1-o4OaOIr_KFyB9HfPpFNZ7fMT7rP1ybkizSYZa