#GET partners
GET http://127.0.0.1:8080/api/partners

### GET tasks_users
GET http://127.0.0.1:8080/api/tasks_users

### GET invoices daily summary
GET http://127.0.0.1:8080/api/invoices_daily_summary

### GET partners
GET https://walrus-app-goxso.ondigitalocean.app/api/partners


### get outmine-settings
GET https://outmine-server-789kp.ondigitalocean.app/api/outmine-settings

### get tasks
GET https://outmine-server-789kp.ondigitalocean.app/api/tasks

###
GET https://walrus-app-goxso.ondigitalocean.app/api/tasks_users

### get invoices
GET  http://127.0.0.1:5001/api/invoices

### get invoices
GET  https://walrus-app-goxso.ondigitalocean.app/api/invoices_revenue


### get invoices
GET  http://127.0.0.1:5001/api/invoices_revenue

###daily summary
GET  http://127.0.0.1:5001/api/invoices_daily_summary

###daily summary
GET  http://127.0.0.1:5001/api/invoices_daily_summary_2

###weekly summary
GET  https://walrus-app-goxso.ondigitalocean.app/api/invoices_weekly_summary

###weekly summary
GET  http://127.0.0.1:5001/api/invoices_weekly_summary



### get number of unsent messages
GET  http://127.0.0.1:8080/api/message_queue_unsent



### POST Toggle message_send in outmine_settings
POST http://127.0.0.1:8080/api/message_send_toggle

### POST Toggle message_send in outmine_settings
POST http://127.0.0.1:8080/api/tasks_hide_toggle/tg_seesfun

### DELETE message_queue_delete_batch
DELETE http://127.0.0.1:5001/api/message_queue_delete_batch/12345