### POST cooldown
POST http://localhost:8080/api/cooldowns-users
Content-Type: application/json

{
  "tg_data":"{{$dotenv tg_data_live}}",
  "cooldown_id" : "tree",
  "cooldown_sub_id" : "2"
}

### POST cooldown
POST http://localhost:8080/api/cooldowns-users
Content-Type: application/json

{
  "tg_data":"{{$dotenv tg_data_live}}",
  "cooldown_id" : "tree",
  "cooldown_sub_id" : "1"
}

### POST cooldown
POST http://localhost:8080/api/cooldowns-users
Content-Type: application/json

{
  "tg_data":"{{$dotenv tg_data_live}}",
  "cooldown_id" : "rock",
  "cooldown_sub_id" : "1"
}


#### GET /api/cooldowns-users - get all cooldowns for user
GET http://localhost:8080/api/cooldowns-users/1321045031

#### GET /api/cooldowns-users
GET http://localhost:8080/api/cooldowns-users/1321045031/tree/1


### POST cooldown
POST http://localhost:8080/api/cooldowns-users
Content-Type: application/json

{
  "tg_data":"{{$dotenv tg_data_live}}",
  "cooldown_id" : "tg_app_center",
  "cooldown_sub_id" : "1"
}

#### GET /api/cooldowns-users
GET http://localhost:8080/api/cooldowns-users/1321045031/tg_app_center/1

###Get telegramgems by user_id
GET https://outmine-server-789kp.ondigitalocean.app/api/telegramgems/1321045031


###Get cooldown
GET https://walrus-app-goxso.ondigitalocean.app/api/cooldowns-users/1321045031/tg_app_center/1

### POST cooldown
POST https://walrus-app-goxso.ondigitalocean.app/api/cooldowns-users
Content-Type: application/json

{
  "tg_data":"{{$dotenv tg_data_live}}",
  "cooldown_id" : "tg_app_center",
  "cooldown_sub_id" : "1"
}


#### GET /api/cooldowns-users - get all cooldowns for user
GET http://localhost:8080/api/items-users/1321045031/wood/1

#### GET /api/cooldowns-users - get all cooldowns for user
GET http://localhost:8080/api/items-users/1321045031/stone/-1