### AUTH
POST http://localhost:8080/api/validate
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "appPubKey": "{{$dotenv appPubKey}}"
}

### USER LOGIN
POST http://localhost:8080/api/user_last_login
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "appPubKey": "{{$dotenv appPubKey}}"
}


### STREAK
POST http://localhost:8080/api/streak
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "appPubKey": "{{$dotenv appPubKey}}"
}

### STREAK HOURS AGO just for testing, not used in the app
POST http://localhost:8080/api/streakHoursAgo
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "appPubKey": "{{$dotenv appPubKey}}",
    "secret": "{{$dotenv MINT_SECRET}}"
}


### MINT
POST http://localhost:8080/api/mint
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "appPubKey": "{{$dotenv appPubKey}}",
    "secret": "{{$dotenv MINT_SECRET}}"

}

### HEALTH CHECK
GET http://localhost:8080/api/health

### STREAK TO POINTS
GET http://localhost:8080/api/streak_to_points?streak=6

### STREAK TO POINTS - ALL
GET http://localhost:8080/api/streak_to_points

### GET Streak Info
GET http://localhost:8080/api/streak_info?address=0xe52B3ACB63b07599db29Ca24ed8d9C5f1a191da7

### GET Game Item metadata From TokenId
GET http://localhost:8080/api/gameItemFromTokenId?tokenId=12

### GET Streak Milestones To TokenIds mapping
GET http://localhost:8080/api/streak_milestones_to_tokenIds



### GET Game Item metadata From TokenId
GET https://walrus-app-goxso.ondigitalocean.app/api/gameItemFromTokenId?tokenId=12




### GET Streak Milestones To TokenIds mapping
GET https://walrus-app-goxso.ondigitalocean.app/api/streak_milestones_to_tokenIds


### GET Outmine Partner counts
GET http://localhost:8080/api/partners

### GET Outmine Proxy
GET http://localhost:8080/api/proxy?url=https://nft.fragment.com/gift/jellybunny-247.json

### GET Outmine Proxy
GET https://walrus-app-goxso.ondigitalocean.app/api/proxy?url=https://nft.fragment.com/gift/jellybunny-247.json

GET https://corsproxy.io/


###
https://corsproxy.io/?url=https://nft.fragment.com/gift/jellybunny-247.json

###
https://corsproxy.io/?url=https://example.com

###
https://corsproxy.io/?key=37d001a3&url=https://nft.fragment.com/gift/jellybunny-247.json

###
https://nft.fragment.com/gift/jellybunny-247.json